server:
  port: 8055
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  hostname: localhost
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
      routes:
        - id: prestamo-service
          uri: lb://prestamo-service
          predicates:
            - Path=/prestamo/**
        - id: registro-service
          uri: lb://registro-service
          predicates:
            - Path=/registro/**
        - id: solicitud-service
          uri: lb://solicitud-service
          predicates:
            - Path=/solicitud/**
        - id: evaluacion-service
          uri: lb://evaluacion-service
          predicates:
            - Path=/evaluacion/**
        - id: seguimiento-service
          uri: lb://seguimiento-service
          predicates:
            - Path=/seguimiento/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS 
            allowedHeaders:
              - "*"

