server:
  port: 8055
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: gateway-service

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: prestamo-service
          uri: http://prestamo-service.default.svc.cluster.local:8080
          predicates:
            - Path=/prestamo/**
        - id: registro-service
          uri: http://registro-service.default.svc.cluster.local:8080
          predicates:
            - Path=/registro/**
        - id: solicitud-service
          uri: http://solicitud-service.default.svc.cluster.local:8080
          predicates:
            - Path=/solicitud/**
        - id: evaluacion-service
          uri: http://evaluacion-service.default.svc.cluster.local:8080
          predicates:
            - Path=/evaluacion/**
        - id: seguimiento-service
          uri: http://seguimiento-service.default.svc.cluster.local:8080
          predicates:
            - Path=/seguimiento/**


