server:
  port: 8055
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: gateway-service

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: registro-service
          uri: http://registro-service.default.svc.cluster.local:8080
          predicates:
            - Path=/registro/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://127.0.0.1:*"
              - "http://localhost:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

